// components/Footer.tsx
import { motion } from "framer-motion";
import { Send, Github, Twitter, Linkedin, Youtube, MessageCircle } from "lucide-react";
import { Button } from "./ui/button.tsx";
import { Input } from "./ui/input.tsx";
import { Separator } from "./ui/separator.tsx";

const footerLinks = {
  Product: [
    { label: "QR.AI", href: "#" },
    { label: "QR.Block", href: "#" },
    { label: "QR.Cloud", href: "#" },
    { label: "QR.Cyber", href: "#" },
    { label: "View all products", href: "#" }
  ],
  Company: [
    { label: "About", href: "#" },
    { label: "Team", href: "#" },
    { label: "Careers", href: "#" },
    { label: "Blog", href: "#" },
    { label: "Press Kit", href: "#" }
  ],
  Resources: [
    { label: "Documentation", href: "#" },
    { label: "API Reference", href: "#" },
    { label: "Community", href: "#" },
    { label: "Support", href: "#" },
    { label: "Status", href: "#" }
  ],
  Legal: [
    { label: "Privacy Policy", href: "#" },
    { label: "Terms of Service", href: "#" },
    { label: "Security", href: "#" },
    { label: "Compliance", href: "#" },
    { label: "Cookies", href: "#" }
  ]
};

const socialLinks = [
  { icon: Github, href: "#", label: "GitHub" },
  { icon: Twitter, href: "#", label: "Twitter" },
  { icon: Linkedin, href: "#", label: "LinkedIn" },
  { icon: Youtube, href: "#", label: "YouTube" }
];

export function Footer() {
  return (
    <footer className="bg-accent/30 backdrop-blur-xl border-t border-border/50 relative overflow-hidden">
      {/* Enhanced background decoration */}
      <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-secondary/5 to-transparent" />
      <div className="absolute inset-0 mesh-gradient opacity-20" />
      
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Main footer content */}
        <div className="py-20 grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-10">
          {/* Brand column */}
          <div className="col-span-2">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              {/* Enhanced Logo */}
              <div className="flex items-center gap-3 mb-6">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary via-cyan-400 to-secondary flex items-center justify-center shadow-lg shadow-primary/20 group-hover:shadow-xl group-hover:shadow-primary/30 transition-shadow">
                  <span className="text-white font-bold text-lg">QR</span>
                </div>
                <span className="text-2xl font-bold bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">Quantum Rishi</span>
              </div>
              
              <p className="text-gray-400 mb-8 max-w-sm leading-relaxed">
                Building the world&apos;s most trusted sovereign infrastructure for autonomous teams.
              </p>

              {/* Telegram contact */}
              <a
                href="https://t.me/quantumrishi"
                className="inline-flex items-center gap-3 px-5 py-3 rounded-xl bg-gradient-to-r from-primary/10 to-secondary/10 border border-primary/30 hover:border-primary/50 hover:bg-primary/15 transition-all duration-300 group mb-8 backdrop-blur-sm"
              >
                <MessageCircle className="h-5 w-5 text-primary group-hover:scale-110 transition-transform" />
                <span className="text-sm font-medium text-primary">Join us on Telegram</span>
              </a>

              {/* Enhanced Social links */}
              <div className="flex gap-3">
                {socialLinks.map((social, idx) => (
                  <a
                    key={idx}
                    href={social.href}
                    className="w-11 h-11 rounded-xl bg-muted/50 hover:bg-gradient-to-br hover:from-primary/20 hover:to-secondary/20 flex items-center justify-center transition-all duration-300 group border border-border/50 hover:border-primary/30 backdrop-blur-sm hover:scale-110"
                    aria-label={social.label}
                  >
                    <social.icon className="h-5 w-5 text-gray-400 group-hover:text-primary transition-colors" />
                  </a>
                ))}
              </div>
            </motion.div>
          </div>

          {/* Link columns */}
          {Object.entries(footerLinks).map(([category, links], idx) => (
            <motion.div
              key={category}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1, duration: 0.6 }}
            >
              <h3 className="mb-5 font-semibold text-lg">{category}</h3>
              <ul className="space-y-3">
                {links.map((link, linkIdx) => (
                  <li key={linkIdx}>
                    <a
                      href={link.href}
                      className="text-sm text-gray-400 hover:text-primary transition-colors duration-300 hover:translate-x-1 inline-block"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>

        <Separator className="bg-border/50" />

        {/* Newsletter section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          {...{ className: "py-10" }}
        >
          <div className="max-w-md">
            <h3 className="mb-3 text-lg font-semibold">Stay updated</h3>
            <p className="text-sm text-gray-400 mb-5">
              Get the latest updates on new features and product releases.
            </p>
            <form className="flex gap-3" onSubmit={(e) => e.preventDefault()}>
              <Input
                type="email"
                placeholder="your@email.com"
                className="bg-background/50 border-border/50 focus:border-primary/50 backdrop-blur-sm rounded-lg"
              />
              <Button type="submit" className="bg-gradient-to-r from-primary to-cyan-400 hover:from-cyan-400 hover:to-primary text-white shadow-lg shadow-primary/20 hover:shadow-xl hover:shadow-primary/30 transition-all rounded-lg px-6">
                <Send className="h-4 w-4" />
              </Button>
            </form>
          </div>
        </motion.div>

        <Separator className="bg-border/50" />

        {/* Bottom bar */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.3, duration: 0.6 }}
          {...{ className: "py-8 flex flex-col md:flex-row justify-between items-center gap-4" }}
        >
          <div className="text-sm text-gray-500">
            © 2025 Quantum Rishi. All rights reserved.
          </div>
          
          <div className="flex flex-wrap gap-6 text-sm">
            <a href="#" className="text-gray-400 hover:text-primary transition-colors duration-300">
              Privacy Policy
            </a>
            <a href="#" className="text-gray-400 hover:text-primary transition-colors duration-300">
              Terms of Service
            </a>
            <a href="#" className="text-gray-400 hover:text-primary transition-colors duration-300">
              Cookie Settings
            </a>
            <a href="#" className="text-gray-400 hover:text-primary transition-colors duration-300">
              Accessibility
            </a>
          </div>
        </motion.div>

        {/* Enhanced community highlights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4, duration: 0.6 }}
          {...{ className: "pb-10" }}
        >
          <div className="bg-card/50 backdrop-blur-xl border border-border/50 rounded-2xl p-8 hover:border-primary/30 transition-all duration-300">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold">Community highlights</h3>
              <div className="flex gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Twitter className="h-5 w-5 text-primary" />
                </div>
                <div className="p-2 rounded-lg bg-secondary/10">
                  <Linkedin className="h-5 w-5 text-secondary" />
                </div>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                "Latest release: QR.AI v2.0 with federated learning support",
                "Join our upcoming webinar on zero-trust architecture",
                "New case study: How we helped Fortune 500 migrate to sovereign cloud"
              ].map((item, idx) => (
                <div
                  key={idx}
                  className="bg-muted/30 backdrop-blur-sm rounded-xl p-5 text-sm text-gray-400 hover:bg-gradient-to-br hover:from-primary/10 hover:to-secondary/10 hover:text-gray-300 transition-all duration-300 cursor-pointer border border-transparent hover:border-primary/20 group"
                >
                  <div className="flex items-start gap-2">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0 group-hover:scale-150 transition-transform" />
                    <span>{item}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>

      {/* Enhanced decorative gradient */}
      <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-primary via-secondary to-primary opacity-80" />
    </footer>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
	import { Github, Linkedin, Twitter, Mail } from 'lucide-svelte';

	const currentYear = new Date().getFullYear();

	const quickLinks = [
		{ name: 'Home', path: '/' },
		{ name: 'Divisions', path: '/divisions' },
		{ name: 'Studio', path: '/studio' },
		{ name: 'Technology', path: '/technology' },
		{ name: 'Contact', path: '/contact' }
	];

	const divisions = [
		{ name: 'QR.AI', path: '/divisions/qr-ai' },
		{ name: 'QR.Block', path: '/divisions/qr-block' },
		{ name: 'QR.Cloud', path: '/divisions/qr-cloud' },
		{ name: 'QR.Cyber', path: '/divisions/qr-cyber' },
		{ name: 'QR.Digi', path: '/divisions/qr-digi' }
	];

	const resources = [
		{ name: 'Documentation', path: '/docs' },
		{ name: 'Blog', path: '/blog' },
		{ name: 'Careers', path: '/careers' },
		{ name: 'Privacy Policy', path: '/privacy' },
		{ name: 'Terms of Service', path: '/terms' }
	];

	const socialLinks = [
		{ name: 'GitHub', icon: Github, url: 'https://github.com/quantum-rishi' },
		{ name: 'LinkedIn', icon: Linkedin, url: 'https://linkedin.com/company/quantum-rishi' },
		{ name: 'Twitter', icon: Twitter, url: 'https://twitter.com/quantum_rishi' },
		{ name: 'Email', icon: Mail, url: 'mailto:contact@quantum-rishi.com' }
	];
</script>

<footer class="border-t border-white/10 bg-slate-950">
	<div class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
		<!-- Main Footer Content -->
		<div class="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
			<!-- Brand Section -->
			<div class="space-y-4">
				<div class="flex items-center space-x-3">
					<div
						class="flex size-10 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600"
					>
						<span class="font-display text-xl font-bold text-white">QR</span>
					</div>
					<div class="flex flex-col">
						<span class="font-display text-lg font-bold text-white">Quantum Rishi™</span>
						<span class="text-xs text-gray-400">Intelligent Systems</span>
					</div>
				</div>
				<p class="text-sm text-gray-400">
					Building intelligent autonomous systems for a secure, scalable, and future-ready India.
				</p>
				<div class="flex space-x-4">
					{#each socialLinks as social (social.name)}
						<a
							href={social.url}
							target="_blank"
							rel="noopener noreferrer"
							class="text-gray-400 transition-colors hover:text-white"
							aria-label={social.name}
						>
							<svelte:component this={social.icon} size={20} />
						</a>
					{/each}
				</div>
			</div>

			<!-- Quick Links -->
			<div>
				<h3 class="font-display mb-4 text-sm font-semibold tracking-wider text-white uppercase">
					Quick Links
				</h3>
				<ul class="space-y-2">
					{#each quickLinks as link (link.path)}
						<li>
							<a
								href={link.path}
								data-sveltekit-preload-data
								class="text-sm text-gray-400 transition-colors hover:text-white"
							>
								{link.name}
							</a>
						</li>
					{/each}
				</ul>
			</div>

			<!-- Divisions -->
			<div>
				<h3 class="font-display mb-4 text-sm font-semibold tracking-wider text-white uppercase">
					Divisions
				</h3>
				<ul class="space-y-2">
					{#each divisions as division (division.path)}
						<li>
							<a
								href={division.path}
								data-sveltekit-preload-data
								class="text-sm text-gray-400 transition-colors hover:text-white"
							>
								{division.name}
							</a>
						</li>
					{/each}
				</ul>
			</div>

			<!-- Resources -->
			<div>
				<h3 class="font-display mb-4 text-sm font-semibold tracking-wider text-white uppercase">
					Resources
				</h3>
				<ul class="space-y-2">
					{#each resources as resource (resource.path)}
						<li>
							<a
								href={resource.path}
								data-sveltekit-preload-data
								class="text-sm text-gray-400 transition-colors hover:text-white"
							>
								{resource.name}
							</a>
						</li>
					{/each}
				</ul>
			</div>
		</div>

		<!-- Bottom Bar -->
		<div
			class="mt-12 flex flex-col items-center justify-between space-y-4 border-t border-white/10 pt-8 md:flex-row md:space-y-0"
		>
			<p class="text-sm text-gray-400">
				© {currentYear} Quantum Rishi™. All rights reserved.
			</p>
			<div class="flex space-x-6">
				<a
					href="/privacy"
					data-sveltekit-preload-data
					class="text-sm text-gray-400 transition-colors hover:text-white"
				>
					Privacy Policy
				</a>
				<a
					href="/terms"
					data-sveltekit-preload-data
					class="text-sm text-gray-400 transition-colors hover:text-white"
				>
					Terms of Service
				</a>
				<a
					href="/sitemap"
					data-sveltekit-preload-data
					class="text-sm text-gray-400 transition-colors hover:text-white"
				>
					Sitemap
				</a>
			</div>
		</div>

		<!-- Tech Badge -->
		<div class="mt-8 text-center">
			<p class="text-xs text-gray-500">
				Built with <span class="text-indigo-400">SvelteKit</span> •
				<span class="text-cyan-400">TailwindCSS</span> •
				<span class="text-purple-400">TypeScript</span>
			</p>
		</div>
	</div>
</footer>
